@baseUrl = http://localhost:3001/api/persons/

# @name createPerson
POST {{baseUrl}} HTTP/1.1
Content-Type: application/json

{
    "name": "Testi Käyttäjä",
    "number": "050 444 3333"
}

###

@personId = {{createPerson.response.body.$.id}}

PUT {{baseUrl}}{{personId}} HTTP/1.1
Content-Type: application/json

{
    "name": "Testi Käyttäjä",
    "number": "050 444 2222"
}

###
DELETE {{baseUrl}}{{personId}}
